version: "3.7"

services:
  prometheus:
    image: prom/prometheus:v2.50.1
    networks:
      - public
    volumes:
      - prometheus_data:/etc/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    configs:
      - source: prom
        target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: grafana/grafana:10.3.4
    networks:
      - public
    volumes:
      - grafana_data:/var/lib/grafana
    configs:
      - source: static
        target: /etc/grafana/provisioning/datasources/provisioning.yml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_SECURITY_ADMIN_USER=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  node-exporter:
    image: prom/node-exporter:v1.7.0
    ports:
      - "9100:9100"
    command:
      - "--path.sysfs=/host/sys"
      - "--path.procfs=/host/proc"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
      - "--no-collector.ipvs"
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    volumes:
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    networks:
      - public

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    command: -logtostderr -docker_only
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    networks:
      - public

networks:
  public:
    external: true

volumes:
  grafana_data:
    external: true
  prometheus_data:
    external: true

configs:
  static:
    file: ./monitoring/provisioning.yml
    name: provisioning
  prom:
    file: ./monitoring/prometheus.yml
    name: prometheusv2
