services:
  prometheus:
    image: prom/prometheus:v3.0.1
    networks:
      - public
    volumes:
      - prometheus_data:/etc/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    configs:
      - source: prom
        target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: grafana/grafana:11.4.0
    networks:
      - public
    volumes:
      - grafana_data:/var/lib/grafana
    configs:
      - source: static
        target: /etc/grafana/provisioning/datasources/provisioning.yml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_SECURITY_ADMIN_USER=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
        - "traefik.http.routers.grafana.service=grafana"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
        - "traefik.docker.network=public"
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  node-exporter:
    image: prom/node-exporter:v1.8.2
    ports:
      - "9100:9100"
    command:
      - "--path.sysfs=/host/sys"
      - "--path.procfs=/host/proc"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
      - "--no-collector.ipvs"
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    volumes:
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    networks:
      - public

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.2
    command: -logtostderr -docker_only
    ports:
      - "8080:8080"
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    networks:
      - public

  loki:
    image: grafana/loki:3.2.1
    ports:
      - "3100:3100"
    networks:
      - public

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - loki
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   networks:
  #     - public

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:3.2.1
    environment:
      LOKI_URL: http://loki:3100/loki/api/v1/push
    volumes:
      - ./monitoring/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    networks:
      - public

networks:
  public:
    external: true

volumes:
  grafana_data:
    external: true
  prometheus_data:
    external: true

configs:
  static:
    file: ./monitoring/provisioning.yml
    name: provisioning
  prom:
    file: ./monitoring/prometheus.yml
    name: prometheus
