version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    ports:
      - 80:80
      - 443:443
    networks:
      - public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.rule=Host(`console.falcon.local`)"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    configs:
      - source: static
        target: /etc/traefik/traefik.yml

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    image: traefik/whoami
    networks:
      - public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami.rule=Host(`whoami.falcon.local`)"

configs:
  static:
    file: ./traefik/static.yml

networks:
  public:
    external: true
